# Users schema

# --- !Ups

create table "logininfo" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
"providerID" VARCHAR NOT NULL,
"providerKey" VARCHAR NOT NULL);

create table "oauth1info" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"token" VARCHAR NOT NULL,"secret" VARCHAR NOT NULL,"loginInfoId" BIGINT NOT NULL);
create table "oauth2info" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"accesstoken" VARCHAR NOT NULL,"tokentype" VARCHAR,"expiresin" INTEGER,"refreshtoken" VARCHAR,"logininfoid" BIGINT NOT NULL);
create table "passwordinfo" (
    "hasher" VARCHAR NOT NULL,
    "password" VARCHAR NOT NULL,
    "salt" VARCHAR,
    "loginInfoId" BIGINT NOT NULL);

create table "user" (
    "userID" VARCHAR NOT NULL PRIMARY KEY,
    "firstName" VARCHAR,
    "lastName" VARCHAR,
    "fullName" VARCHAR,
    "email" VARCHAR,
    "avatarURL" VARCHAR);

create table "userlogininfo" (
    "userID" VARCHAR NOT NULL,
    "loginInfoId" BIGINT NOT NULL);

# --- !Downs

drop table "userlogininfo";
drop table "user";
drop table "passwordinfo";
drop table "oauth2info";
drop table "oauth1info";
drop table "logininfo";

